name:                sequence-alignment-haskell
version:             0.1.0.0
github:              "hubbards/sequence-alignment-haskell"
license:             MIT
author:              "Spencer Hubbard"
copyright:           "2018 Spencer Hubbard"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/hubbards/sequence-alignment-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- pretty
- bytestring
- array
- containers

library:
  source-dirs: src

executables:
  app-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sequence-alignment-haskell

tests:
  sequence-alignment-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sequence-alignment-haskell
    - doctest >= 0.8
