name: sequence-alignment-haskell
version: 0.1.0.0
github: "hubbards/sequence-alignment-haskell"
license: MIT
author:  "Spencer Hubbard"
copyright: "2018 Spencer Hubbard"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis: Short description of your package
# category: Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on Github at <https://github.com/hubbards/sequence-alignment-haskell#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options: -Wall

library:
  source-dirs: src
  exposed-modules:
  - Align
  - Fib
  dependencies:
  - transformers
  - bytestring
  - containers
  - array
  - pretty

executables:
  app-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
    - sequence-alignment-haskell
    - bytestring
    - pretty

tests:
  tests:
    main: Main.hs
    source-dirs: test
    dependencies:
    - sequence-alignment-haskell
    - filepath
    - doctest >= 0.8
